#!/usr/bin/env bash

check_factor()
{
	if [ $# -ne 3 ];
	then
		args=("$@")
		track=0
		val2=1
		for a in ${args[*]};
		do
			if [ $track -gt 1 ];
			then
				val2=$(echo $a*$val2 | bc)
			fi
			track=$((track + 1))
		done
	else
		val2=$3
	fi

	val1=$2
	val=$(echo "$1" | tr ':' '=')

	answer=$(echo "if($val2 > $val1) 1 else 0" | bc)
		if ((answer == 1)); then
			valcp=$val1
			val1=$val2
			val2=$valcp
		fi

	echo "$val$val1*$val2"
}

if [ $# -ne 1 ]
then
	echo 'Usage: factors <file>'
	exit 1
else

	while read i
	do

		answer=$(factor "$i")
		check_factor $answer

	done < "$1"
fi