#!/usr/bin/python3

import sys

def fac_finder():
	"""
	function for factoring
	"""
	try:
		w_doc = sys.argv[1]
		with open(w_doc) as w_file:
			for w_digits in w_file:
			w_digits = int(w_digits)
			if w_digits % 2 == 0:
				print("{}={}*{}".format(w_digits, w_digits // 2, 2))
				continue
			k = 3
			while k < w_digits // 2:
				if w_digits % k == 0:
					print("{}={}*{}".format(w_digits, w_digits // k, k))
					break
				k = k + 2
			if k == (w_digits // 2) + 1:
				print("{}={}*{}".format(w_digits, w_digits, 1))
	except (IndexError):
		pass



fac_finder()